name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi Deployment di Server Batam
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/erp-hris-backend
            git pull origin master
            npm ci
            npx prisma generate
            npx prisma migrate deploy
            npm run build
            pm2 restart hris-backend